[build]
publish = "build"
command = "yarn build"
functions = "functions/"

[[redirects]]
  from = "/latestversion"
  to = "/.netlify/functions/latestversion"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "https://edgemesh.kubeedge.io"
  to = "https://edgemesh.netlify.app"
  status = 200
  force = true

